import './globals.css';

import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';

import ReactQueryProvider from '@/app/_component/ReactQueryProvider';

import RecoilRootProvider from './_component/RecoilRootProvider';

const notoSansKr = Noto_Sans_KR({
  preload: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={notoSansKr.className}>
        <ReactQueryProvider>
          <RecoilRootProvider>{children}</RecoilRootProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
