import './globals.css';

import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import React from 'react';

import ReactQueryProvider from '@/app/_component/ReactQueryProvider';
import ModalProvider from '@/share/modal/ModalProvider';

import CheckAuth from './_component/CheckAuth';
import RecoilRootProvider from './_component/RecoilRootProvider';

const notoSansKr = Noto_Sans_KR({
  preload: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={notoSansKr.className}>
        <RecoilRootProvider>
          <ReactQueryProvider>
            <CheckAuth />
            <AntdRegistry>{children}</AntdRegistry>
          </ReactQueryProvider>
          <ModalProvider />
        </RecoilRootProvider>
      </body>
    </html>
  );
}
